### ISSUE TITLE
Enable JsonParser Features like ALLOW_COMMENTS, ALLOW_YAML_COMMENTS

### ISSUE THREAD

**Issue by w3scme** [adjohnson916/jackson-json-reference#21]
Currently there is no way to use the Jacksons Paser Features (e.g. ALLOW_COMMENTS, ALLOW_YAML_COMMENTS), because the JsonContext uses its own ObjectMapper.

I would recommend set the mapper via Constructor.

In this way it is possible to use the mapper of JsonReferenceProcessor the following way

JsonContext context = new JsonContext(this.mapper, file);

With that small changes you could

* enable the Features for an ObjectMapper
* inctect this mapper in JsonReferenceProcessor like before

 I am totally new github user. Is it possible to create that feature myself?

Kind regards

**Comment by adjohnson916** [comment]
@w3scme Thanks for the suggestion.

I've improved the custom object mapper factory support to allow complete control rather than forcing the default object mapper for `.json` file extensions.

Also I've updated [README settings](https://github.com/adjohnson916/jackson-json-reference/blob/master/README.md#settings) with an example showing how to allow JSON comments.

Released this change with version `0.2.0` and pushed to BinTray so it should trickle through their caches soon.

**Comment by w3scme** [comment]
@adjohnson916 Thank your for fixing it that fast.

But the updated gredle config in the readme does not work for me.

If I use 

compile 'me.andrz.jackson:jackson-json-reference-core:0.2.0'

I will get: **Could not GET 'https://dl.bintray.com/adjohnson916/maven/me/andrz/jackson/jackson-json-reference-core/0.2.0/jackson-json-reference-core-0.2.0.pom'. Received status code 401 from server: Unauthorized**

If I use 

compile 'me.andrz.jackson:jackson-json-reference:0.2.0' I do not get errors from gradle, but I do not get the jars, too.

**Comment by adjohnson916** [comment]
@w3scme Yes, I've been having issues with Bintray lately - it doesn't seem ti publish my artifacts.

You can get the JARs from this release on GitHub I've just created: https://github.com/adjohnson916/jackson-json-reference/releases/tag/jackson-json-reference-0.2.0
